### ISSUE TITLE
Mailchimp opt-in fails when site is HTTPS

### ISSUE THREAD

**Issue by cklosowski** [groundhoggwp/holler-box#1]
The setting to include the MailChimp list URL for a Holler causes a mixed content error and then a JavaScript issue where an HTTPS page cannot make an HTTP AJAX request, when the email optin is used.

Moving to using the API should work, instead of directly posting to the form URL.

On page load:
`Mixed Content: The page at 'https://chrisk.io/' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://filament-studios.us2.list-manage1.com/subscribe/post-json?u=xxxxxxxxxxxxxxxxxxx'. This endpoint should be made available over a secure connection.`

Firing the AJAX to subscribe the user:
`jquery.js?ver=1.12.4:4 Mixed Content: The page at 'https://chrisk.io/' was loaded over HTTPS, but requested an insecure script 'http://filament-studios.us2.list-manage1.com/subscribe/post-json?u=7e77a38f…xxxxxxxxxxxxxxxxxxx&EMAIL=chris%40easydigitaldownloads.com&hwp_hp=&_=xxxxxxxxxxxxxxxxxxx'. This request has been blocked; the content must be served over HTTPS.`

**Comment by cklosowski** [comment]
As a note, I did reach out to MailChimp to see why their hosted forms cannot load over HTTPS (which would effectively solve this problem), but they haven't responded yet:
https://twitter.com/cklosowski/status/872679997240102913

**Comment by cklosowski** [comment]
I guess the other option would be to have the AJAX request fire an admin-ajax.php action that sends the request via `wp_remote_post`, since PHP doesn't care if the request is over HTTP.

**Comment by scottopolis** [comment]
Hmm, you put https in your form url? I'm not sure why that wouldn't work.  I'm not actually using the MC form, just pulling that url into an ajax request.

**Comment by cklosowski** [comment]
@scottopolis Yep, I've tried making the URL `https://` but that fails the secure connection because MailChimp hosted forms can only load over HTTP, they do not have SSLs setup for all the subdomains that occur.


![](https://pbs.twimg.com/media/DBxh0AMUMAAN9VR.jpg)

**Comment by scottopolis** [comment]
Currently rewriting this to use the API, should fix this issue.

**Comment by scottopolis** [comment]
@cklosowski should be fixed, mind giving the master branch a test? You'll have to add your api key in the settings, then add the list ID in the holler box.

01c434d3b2cded785468da38772780fe04d3d270

**Comment by cklosowski** [comment]
@scottopolis yep! Will give it a shot shortly.

**Comment by cklosowski** [comment]
Worked like a charm! Closing as fixed, amazing turn around :)
