### ISSUE TITLE
Add action hooks after specific events

### ISSUE THREAD

**Issue by amdrew** [groundhoggwp/holler-box#13]
It would be super neat to get some new action hooks added that fire just after the user has completed a specific action. For example, after the user submits their email address (and the email is sent) and after the user's email has been submitted to MailChimp.

I'd love to be able to mash AffiliateWP and Holler Box together so if a user is referred to the site and completes an action, a referral can be created in AffiliateWP.

**Comment by scottopolis** [comment]
I could add that, would you just be checking for an affwp cookie after the email is submitted?

**Comment by amdrew** [comment]
Yep, after any kind of action we'd grab the affiliate ID if present in the cookies and create a referral 👍 Thanks Scott
