### ISSUE TITLE
Filter to select holler to show.

### ISSUE THREAD

**Issue by Shelob9** [groundhoggwp/holler-box#5]
I'd like (and will submit PR for) a filter that runs before the built-in logic for selecting a holler. It would default to returning null, which would cause existing logic to run. But if it returned a valid ID of a holler, then that one would be shown instead.

**Comment by scottopolis** [comment]
Checking this out now

**Comment by scottopolis** [comment]
@Shelob9 is there a reason you can't use the hwp_display_notification filter for this same purpose? 

    add_filter( 'hwp_display_notification', function( $show_it, $box_id, $post_id ) {
     if( $box_id === 123 ) return true;

     return $show_it;
    }
